### ISSUE TITLE
Faceswap Tab Not Visible

### ISSUE THREAD

**Issue by slaughters85j** [dchatel/vid-faceswap#2]
The repo installed correctly and is showing up in the installed extensions directory page.  After applying and restarting the tab is not present.  It's shown as installed but not tab exists.

SD version: v1.2.1  •  python: 3.10.11  •  torch: 2.0.1  •  xformers: N/A  •  gradio: 3.29.0  •  checkpoint: e1441589a6

![2023-05-17_17-36-17](https://github.com/dchatel/vid-faceswap/assets/9493107/4bbaf85c-8154-46c9-9043-0bd868343797)

**Comment by slaughters85j** [comment]
Error loading script: face_detect.py
Traceback (most recent call last):
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/extensions/batch-face-swap/scripts/face_detect.py", line 10, in <module>
    import mediapipe as mp
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/mediapipe/framework/formats/detection_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)

*** WARNING: Something went wrong when updating to the latest dynamicprompts version. Please install it manually by running the following command:
    /Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/venv/bin/python3.10 -m pip install dynamicprompts==0.25.2

ControlNet v1.1.189
ControlNet v1.1.189
Loading weights [24a393500f] from /Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/models/Stable-diffusion/perfectWorld_v4Baked.safetensors
Creating model from config: /Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Textual inversion embeddings loaded(4): 
Model loaded in 3.3s (load weights from disk: 0.2s, create model: 0.7s, apply weights to model: 1.6s, move model to device: 0.7s, load textual inversion embeddings: 0.1s).
Image Browser: ImageReward is not installed, cannot be used.
Error loading script: face.py
Traceback (most recent call last):
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/extensions/vid-faceswap/scripts/face.py", line 4, in <module>
    from insightface.utils import face_align
ModuleNotFoundError: No module named 'insightface'

Error loading script: frame.py
Traceback (most recent call last):
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/extensions/vid-faceswap/scripts/frame.py", line 2, in <module>
    from scripts.face import Face
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/extensions/vid-faceswap/scripts/face.py", line 4, in <module>
    from insightface.utils import face_align
ModuleNotFoundError: No module named 'insightface'

Error loading script: vid_faceswap.py
Traceback (most recent call last):
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/extensions/vid-faceswap/scripts/vid_faceswap.py", line 21, in <module>
    from scripts.frame import Frame
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/extensions/vid-faceswap/scripts/frame.py", line 2, in <module>
    from scripts.face import Face
  File "/Volumes/Mac 4TB External Storage/Development/ai/stable-diffusion-webui/extensions/vid-faceswap/scripts/face.py", line 4, in <module>
    from insightface.utils import face_align
ModuleNotFoundError: No module named 'insightface'

**Comment by dchatel** [comment]
Try installing insightface. You should get version 0.7.3.
```
pip install -U insightface
```
