### ISSUE TITLE
Error popping mid-video generation

### ISSUE THREAD

**Issue by YomegaPop** [dchatel/vid-faceswap#4]
I am getting an error about 17 seconds in to face swap generation:

Traceback (most recent call last):
  File "C:\Users\kibet\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\kibet\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\kibet\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\kibet\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\kibet\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\kibet\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable\stable-diffusion-webui\extensions\vid-faceswap\scripts\vid_faceswap.py", line 65, in process_video
    dets = FaceDetector_get(frames_data)
  File "C:\stable\stable-diffusion-webui\extensions\vid-faceswap\scripts\face.py", line 13, in FaceDetector_get
    _fa = FaceAnalysis(name='buffalo_l', providers=['CUDAExecutionProvider'])
TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'

Saw some indication that this could be related to onnxruntime so updated this to the latest version in the venv, but a bit stuck on what to try next!

**Comment by sti320a** [comment]
I got same error. Then it was resolved in this thread. Please try it.
https://github.com/dchatel/vid-faceswap/issues/3#issuecomment-1575537122
