### ISSUE TITLE
Error loading script: vid_faceswap.py

### ISSUE THREAD

**Issue by patientx** [dchatel/vid-faceswap#7]
I solved all other problems, moviepy etc. Is it maybe incompatible with latest version of sdwebui ?

`*** Error loading script: vid_faceswap.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-directml\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui-directml\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui-directml\extensions\vid-faceswap\scripts\vid_faceswap.py", line 15, in <module>
        from modules.ui import create_sampler_and_steps_selection, create_seed_inputs, create_refresh_button
    ImportError: cannot import name 'create_seed_inputs' from 'modules.ui' (D:\stable-diffusion-webui-directml\modules\ui.py)`

**Comment by nitinmukesh** [comment]
Did you find solution for this?

**Comment by patientx** [comment]
> Did you find solution for this?

just use facefusion, standalone more capable and lots of options ...
