### ISSUE TITLE
Error loading script: vid_faceswap.py

### ISSUE THREAD

**Issue by itAsia** [dchatel/vid-faceswap#9]
Any idea ? It is very hard to correct as it doesn't say anything about a missing module...

Thanks :)

++

*** Error loading script: vid_faceswap.py
    Traceback (most recent call last):
      File "/home/stef/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/stef/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/stef/stable-diffusion/stable-diffusion-webui/extensions/vid-faceswap/scripts/vid_faceswap.py", line 15, in <module>
        from modules.ui import create_sampler_and_steps_selection, create_seed_inputs, create_refresh_button
    ImportError: cannot import name 'create_seed_inputs' from 'modules.ui' (/home/stef/stable-diffusion/stable-diffusion-webui/modules/ui.py)

**Comment by dchatel** [comment]
That extension is discontinued for a while now. I think it's incompatible with A1111 since 1.4 or 1.5 I don't remember exactly.

**Comment by itAsia** [comment]
ok, thanks
